### ISSUE TITLE
Resize volume after creation?

### ISSUE THREAD

**Issue by Bungeefan** [ashald/docker-volume-loopback#3]
Is there a possibility to resize an already existing volume?

For example, you created a volume with 1GiB and now want to extend it to 4GiB, without losing any data.

**Comment by ashald** [comment]
It's been a while since I touched this so my memory might be somewhat off...

IIRC, the plugin does not have such an option implemented. That being said, since it's just a file backed block device, you should be able to handle this manually as a workaround. Just guessing from the top of my head, If I were doing this, I'd start by trying this:
1. Create a new file of the desired size (use `truncate`/`falocate`/`dd similar to how the plugin does it)
2. Use `dd` to copy the the bytes from the original volume (I don't recall if it can read from a file, so maybe you'd want to mount both as block devices and then use `dd`
3. Last step is so grow the FS within the larger file - I don't recall which command does that, but there is one for sure

Definitely sounds like a useful feature to have in the plugin though. 🤔

**Comment by Bungeefan** [comment]
Thanks for your response!

Yeah, we came to the same conclusion with the shell commands, but without creating a new file.
If anybody has the same requirements, here are the commands that worked for us (using XFS):
```sh
# Increase file size
sudo fallocate -l 10G /var/lib/docker-volume-loopback/my_vol
# Update loop device
sudo losetup -c /dev/loopX
# Grow XFS
sudo xfs_growfs /dev/loopX
```

Check with:
```sh
sudo df -h /dev/loopX
```
The same should be possible for EXT4, but with a different grow command.

However, it would be really nice if this was supported through native Docker APIs, but I am not sure if Docker even supports providing new options or modifying an existing volume.
